-- Vendor orders on purchase orders: whole invoices tracked against a PO.
--
-- A purchase order's lines track books item by item -- how many are wanted,
-- how many have been bought. Some books are not bought that way: someone else
-- orders them from a vendor, and BookBin's side is only to pay the invoice,
-- or to pay it and deal with the delivery. Those are tracked here at the
-- invoice level instead.
--
-- A PO names the vendors it expects orders from, each with where their orders
-- ship to. That choice decides what is left to do with an invoice:
--
--   warehouse  -- it only needs paying; somebody else receives it.
--   me         -- it needs paying AND receiving here.
--
-- Invoices are then linked to a tracked vendor by hand. Matching by vendor and
-- date alone would put an invoice dated before the PO was created on no PO,
-- and an unrelated order from the same vendor on this one.

create table if not exists public.purchase_order_vendors (
  id                 bigint generated by default as identity primary key,
  purchase_order_id  bigint not null references public.purchase_orders(id) on delete cascade,
  vendor_id          bigint not null references public.vendors(id) on delete cascade,
  ships_to           text not null default 'warehouse' check (ships_to in ('warehouse', 'me')),
  notes              text,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  -- One entry per vendor per PO; a second would split its invoices between
  -- two places that are meant to be the same thing.
  unique (purchase_order_id, vendor_id)
);

-- invoice_id is the primary key, which is the rule "an invoice belongs to at
-- most one purchase order" in a form the database enforces rather than one
-- the app has to remember. Two people linking the same invoice at once get
-- one success and one refusal, not a double-counted bill.
create table if not exists public.purchase_order_invoices (
  invoice_id                bigint primary key references public.incoming_invoices(id) on delete cascade,
  purchase_order_vendor_id  bigint not null references public.purchase_order_vendors(id) on delete cascade,
  created_at                timestamptz not null default now()
);

create index if not exists idx_po_vendors_po on public.purchase_order_vendors(purchase_order_id);
create index if not exists idx_po_invoices_po_vendor on public.purchase_order_invoices(purchase_order_vendor_id);

drop trigger if exists touch_updated_at on public.purchase_order_vendors;
create trigger touch_updated_at
  before update on public.purchase_order_vendors
  for each row execute function public.touch_updated_at();

-- Same rule as every other business table: signed-in staff, nobody else.
alter table public.purchase_order_vendors  enable row level security;
alter table public.purchase_order_invoices enable row level security;

revoke all on public.purchase_order_vendors  from anon;
revoke all on public.purchase_order_invoices from anon;

drop policy if exists staff_all on public.purchase_order_vendors;
create policy staff_all on public.purchase_order_vendors
  for all to authenticated
  using (public.is_staff())
  with check (public.is_staff());

drop policy if exists staff_all on public.purchase_order_invoices;
create policy staff_all on public.purchase_order_invoices
  for all to authenticated
  using (public.is_staff())
  with check (public.is_staff());
