-- BookBin schema, ported from db/schema.sql (SQLite) to Postgres.
--
-- Deliberate differences from the SQLite original, all of them things SQLite
-- was too permissive about:
--
--   * Money and quantities are numeric, not REAL. Floating point cannot
--     represent 0.10 exactly, so REAL totals drift by fractions of a cent as
--     they accumulate. Per-unit figures keep 4 decimal places (a unit cost
--     genuinely can be fractional once shipping is apportioned across a
--     line); anything representing a settled amount of money keeps 2.
--   * paid / received / is_inventory are real booleans, not 0/1 integers.
--   * created_at is timestamptz, not a naive UTC string.
--   * item_cost_snapshots.breakdown is jsonb, not TEXT holding JSON, so it is
--     queryable instead of opaque.
--   * Every table people edit carries updated_at, maintained by trigger. That
--     is what makes it possible to detect "someone else changed this row while
--     you had it open" -- the whole point of moving off a single-writer file.
--
-- Ids stay bigint identity with GENERATED BY DEFAULT rather than ALWAYS, so
-- the existing SQLite rows can be imported with their current ids intact and
-- every foreign key between them still lines up.

-- ---------------------------------------------------------------- utilities

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $fn$
begin
  new.updated_at = now();
  return new;
end;
$fn$;

-- ----------------------------------------------------------------- settings

create table if not exists public.settings (
  id                    integer primary key check (id = 1),
  company_name          text not null default '',
  company_address       text not null default '',
  company_logo_path     text,
  incoming_prefix       text not null default 'BILL-',
  incoming_next_number  integer not null default 1,
  outgoing_prefix       text not null default 'INV-',
  outgoing_next_number  integer not null default 1,
  low_stock_threshold   numeric(14,4) not null default 5,
  cost_markup_percent   numeric(8,4) not null default 2,
  updated_at            timestamptz not null default now()
);

insert into public.settings (id) values (1) on conflict (id) do nothing;

-- ------------------------------------------------------- vendors, customers

create table if not exists public.vendors (
  id            bigint generated by default as identity primary key,
  name          text not null,
  contact_name  text,
  email         text,
  phone         text,
  address       text,
  notes         text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create table if not exists public.customers (
  id            bigint generated by default as identity primary key,
  name          text not null,
  contact_name  text,
  email         text,
  phone         text,
  address       text,
  notes         text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- -------------------------------------------------------------------- items

create table if not exists public.items (
  id                bigint generated by default as identity primary key,
  sku               text,
  name              text not null,
  description       text,
  unit              text not null default 'ea',
  is_inventory      boolean not null default true,
  quantity_on_hand  numeric(14,4) not null default 0,
  default_cost      numeric(14,4) not null default 0,
  default_price     numeric(14,4) not null default 0,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

-- -------------------------------------------------------- incoming invoices

create table if not exists public.incoming_invoices (
  id               bigint generated by default as identity primary key,
  vendor_id        bigint references public.vendors(id) on delete set null,
  invoice_number   text not null,
  invoice_date     date not null,
  notes            text,
  total            numeric(14,2) not null default 0,
  shipping_tax     numeric(14,2) not null default 0,
  paid             boolean not null default false,
  received         boolean not null default false,
  attachment_path  text,
  attachment_name  text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create table if not exists public.incoming_invoice_lines (
  id           bigint generated by default as identity primary key,
  invoice_id   bigint not null references public.incoming_invoices(id) on delete cascade,
  item_id      bigint references public.items(id) on delete set null,
  description  text not null,
  quantity     numeric(14,4) not null default 0,
  unit_cost    numeric(14,4) not null default 0,
  line_total   numeric(14,2) not null default 0
);

-- -------------------------------------------------------- outgoing invoices

create table if not exists public.outgoing_invoices (
  id               bigint generated by default as identity primary key,
  customer_id      bigint references public.customers(id) on delete set null,
  invoice_number   text not null,
  invoice_date     date not null,
  notes            text,
  total            numeric(14,2) not null default 0,
  status           text not null default 'draft',
  attachment_path  text,
  attachment_name  text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create table if not exists public.outgoing_invoice_lines (
  id           bigint generated by default as identity primary key,
  invoice_id   bigint not null references public.outgoing_invoices(id) on delete cascade,
  item_id      bigint references public.items(id) on delete set null,
  description  text not null,
  quantity     numeric(14,4) not null default 0,
  unit_price   numeric(14,4) not null default 0,
  line_total   numeric(14,2) not null default 0
);

-- ------------------------------------------------------ inventory + costing

-- Audit log of every stock change, so on-hand quantities are always
-- explainable and invoice edits/deletes can correctly reverse prior effects.
-- Append-only, hence no updated_at.
create table if not exists public.inventory_adjustments (
  id           bigint generated by default as identity primary key,
  item_id      bigint not null references public.items(id) on delete cascade,
  delta        numeric(14,4) not null,
  reason       text not null,
  source_type  text not null,
  source_id    bigint,
  created_at   timestamptz not null default now()
);

-- One row per cost/price recalculation for an item, so a later question about
-- "why is this priced the way it is" can be answered even if the incoming
-- invoices that fed into it are later edited or deleted. Also append-only.
create table if not exists public.item_cost_snapshots (
  id              bigint generated by default as identity primary key,
  item_id         bigint not null references public.items(id) on delete cascade,
  cost            numeric(14,4) not null,
  price           numeric(14,4) not null,
  markup_percent  numeric(8,4) not null,
  breakdown       jsonb not null,
  created_at      timestamptz not null default now()
);

-- ---------------------------------------------------------- purchase orders

create table if not exists public.purchase_orders (
  id          bigint generated by default as identity primary key,
  name        text not null,
  status      text not null default 'open',
  closed_at   timestamptz,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists public.purchase_order_items (
  id                      bigint generated by default as identity primary key,
  purchase_order_id       bigint references public.purchase_orders(id) on delete cascade,
  item_id                 bigint references public.items(id) on delete set null,
  name                    text not null,
  edition                 text,
  isbn                    text,
  quantity_wanted         numeric(14,4) not null default 1,
  max_price               numeric(14,4) not null default 0,
  notes                   text,
  frozen_bought_quantity  numeric(14,4),
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);

-- ------------------------------------------------------------------ indexes

create index if not exists idx_incoming_lines_invoice on public.incoming_invoice_lines(invoice_id);
create index if not exists idx_outgoing_lines_invoice on public.outgoing_invoice_lines(invoice_id);
create index if not exists idx_adjustments_item on public.inventory_adjustments(item_id);
create index if not exists idx_adjustments_source on public.inventory_adjustments(source_type, source_id);
create index if not exists idx_cost_snapshots_item on public.item_cost_snapshots(item_id);
create index if not exists idx_purchase_order_items_item on public.purchase_order_items(item_id);
create index if not exists idx_purchase_order_items_po on public.purchase_order_items(purchase_order_id);

-- -------------------------------------------------------- updated_at wiring

do $wire$
declare
  t text;
begin
  foreach t in array array[
    'settings', 'vendors', 'customers', 'items',
    'incoming_invoices', 'outgoing_invoices',
    'purchase_orders', 'purchase_order_items'
  ]
  loop
    execute format('drop trigger if exists touch_updated_at on public.%I', t);
    execute format(
      'create trigger touch_updated_at before update on public.%I '
      'for each row execute function public.touch_updated_at()', t);
  end loop;
end;
$wire$;
